### PR TITLE
example directory restructured

### PR DESCRIPTION
**Pull request by aeroaks**
Regarding #95 
- [x] Converting the .py scripts in examples to Jupyter notebooks
- [x] Remove the old examples/examples-notebook directory and the .py scripts in examples
- [x] Make sure these work from mybinder by adding a command to install PyFME

### CODE REVIEW

**Comment by aqreed** [comment]
@aeroaks I would like to keep the `.py` examples files, as they will be needed to simulate and tests new developments. Also, not everyone uses notebooks (I don't, for example), so what I propose is to keep the `.ipynb` files in the old directory.

**Comment by Juanlu001** [comment]
@aqreed We agreed the other day not to duplicate the examples - it's true that we need tests, but those should be unit tests. Keeping two versions of the examples is a mess, I'm -1 on keeping the .py files.

**Comment by aeroaks** [comment]
@aqreed  I have not used it but I think that there is a way in which you can convert notebook file to scripts.

**Comment by aqreed** [comment]
@Juanlu001 well I do think py examples and nb examples should be **two separate entities**, Jupyter notebooks are a good thing but we should not impose its use neither to visitors or to developers.

**Comment by miqlar** [comment]
I am +1 to having both notebooks and .py's. 

Notebooks are nice but annoying for fast checks and copypastes.

**Comment by Juanlu001** [comment]
Pending review:

* [ ] Check links in `index.ipynb`
* [ ] Check that the notebooks match the scripts (perhaps using `jupyter nbconvert Example.ipynb --to python`)
* [ ] Check that the notebooks contain all output and plots

Who wants to review the pull request based on these bullet points? You can check out the changes using these commands:

```
git checkout -b aeroaks-master master
git pull git://github.com/aeroaks/PyFME.git master
```

**Comment by aqreed** [comment]
When doing `jupyter nbconvert Example.ipynb --to python` this line is added that crashes when executing the script: `get_ipython().magic('matplotlib inline')`...after deleting it the script runs fine. 

@aeroaks I will send you a pull request with the modifications get all the plots in the examples 006 and 007 (my bad, I forgot to uncomment some of them in the precious PR). Also, example 005 was left executed too so I cleaned it up.

**Comment by Juanlu001** [comment]
> When doing `jupyter nbconvert Example.ipynb --to python` this line is added that crashes when executing the script: `get_ipython().magic('matplotlib inline')`...after deleting it the script runs fine. 

You have to run your script with ipython:

```
$ ipython example.py
```

Then get_ipython will be already in global context.

(Source: stackoverflow.com/a/32539282/554319)

**Comment by Juanlu001** [comment]
By the way, it seems like the conversion template con be modified, in case it's interesting:

http://nbconvert.readthedocs.io/en/latest/customizing.html

**Comment by AlexS12** [comment]
I have merged the branch so now can have both options at the same time. Nevertheless, as I see that @aqreed seems has more changes to do, we can discuss them in a new pull request

**Pull request merged**
