### PR TITLE
coordinates.py fixed

### PR DESCRIPTION
**Pull request by JuanMatSa**
As Juanlu noticed, the check_theta_phi_psi_range function was not checking the phi angle. Now it is.

### CODE REVIEW

**Comment by JuanMatSa** [comment]
Still have to modify the test_coordinates.py file

**Comment by AlexS12** [comment]
I have just tried to remove the `m = ...` dummy variable and all the test are passing.

You can find more information about this kind of test here: https://pytest.org/latest/assert.html

**Comment by Juanlu001** [comment]
As @AlexS12 says, it would work fine without saving the result to a variable as well. The function call will run nevertheless, so you can safely remove the assign operation.

**Comment by AlexS12** [comment]
@JuanMatSa you have a pull request to your branch so you don't need to remove it yourself again :wink:

**Comment by JuanMatSa** [comment]
ok thank you @AlexS12, I don't know why It didn't work yesterday.
Merged, so pull request can be aproved. =D

**Pull request merged**
